// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxuoicbppqlyfcgvabny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94dW9pY2JwcHFseWZjZ3ZhYm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTU1MDgsImV4cCI6MjA2OTQzMTUwOH0.jaUN1vv3BtvvErjP8nPUyu4QiJ5aRorJOEIVtX1dKKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});